kind: Service
apiVersion: v1
metadata:
  name: hello-world-service
  namespace: dev
spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer